#version 330
uniform vec3 _WorldSpaceCameraPos;
uniform vec4 _ProjectionParams;
uniform vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform vec4 hlslcc_mtx4x4unity_WorldToObject[4];
uniform vec4 unity_WorldTransformParams;
uniform vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform vec4 hlslcc_mtx4x4u_UniqueShadowMatrix[4];
in vec4 in_POSITION0;
in vec2 in_TEXCOORD0;
in vec2 in_TEXCOORD1;
in vec3 in_NORMAL0;
in vec4 in_TANGENT0;
in vec4 in_COLOR0;
out vec4 vs_TEXCOORD0;
out vec3 vs_TEXCOORD1;
out vec4 vs_TEXCOORD2; //worldTangent
out vec4 vs_TEXCOORD3; //worldBinormal
out vec4 vs_TEXCOORD4; //worldNormal
out vec4 vs_TEXCOORD5;
out vec4 vs_TEXCOORD6;
vec4 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat2;
vec3 u_xlat3;
float u_xlat13;
void main(){
(u_xlat0 = (in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1]));
(u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx) + u_xlat0));
(u_xlat0 = ((hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz) + u_xlat0));
(u_xlat0 = (u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3]));
(u_xlat1 = (u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1]));
(u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx) + u_xlat1));
(u_xlat1 = ((hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz) + u_xlat1));
(u_xlat0 = ((hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww) + u_xlat1));
(gl_Position = u_xlat0);
(vs_TEXCOORD0.xy = in_TEXCOORD0.xy);
(vs_TEXCOORD0.zw = in_TEXCOORD1.xy);
(u_xlat1.xyz = (in_POSITION0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
(u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_POSITION0.xxx) + u_xlat1.xyz));
(u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_POSITION0.zzz) + u_xlat1.xyz));
(u_xlat1.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[3].xyz * in_POSITION0.www) + u_xlat1.xyz));
(u_xlat2.xyz = ((-u_xlat1.xyz) + _WorldSpaceCameraPos.xyz));
(vs_TEXCOORD1.xyz = ((in_COLOR0.xyz * vec3(9.9999997e-06, 9.9999997e-06, 9.9999997e-06)) + u_xlat2.xyz));
(u_xlat2.xyz = (in_TANGENT0.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
(u_xlat2.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * in_TANGENT0.xxx) + u_xlat2.xyz));
(u_xlat2.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * in_TANGENT0.zzz) + u_xlat2.xyz));
(u_xlat13 = dot(u_xlat2.xyz, u_xlat2.xyz));
(u_xlat13 = inversesqrt(u_xlat13));
(vs_TEXCOORD2.xyz = (vec3(u_xlat13) * u_xlat2.xyz));
(vs_TEXCOORD2.w = u_xlat1.x);
(u_xlat2.xyz = (in_NORMAL0.zxy * in_TANGENT0.yzx));
(u_xlat2.xyz = ((in_NORMAL0.yzx * in_TANGENT0.zxy) + (-u_xlat2.xyz)));
(u_xlat2.xyz = (u_xlat2.xyz * in_TANGENT0.www));
(u_xlat3.xyz = (u_xlat2.yyy * hlslcc_mtx4x4unity_ObjectToWorld[1].xyz));
(u_xlat2.xyw = ((hlslcc_mtx4x4unity_ObjectToWorld[0].xyz * u_xlat2.xxx) + u_xlat3.xyz));
(u_xlat2.xyz = ((hlslcc_mtx4x4unity_ObjectToWorld[2].xyz * u_xlat2.zzz) + u_xlat2.xyw));
(u_xlat13 = dot(u_xlat2.xyz, u_xlat2.xyz));
(u_xlat13 = inversesqrt(u_xlat13));
(u_xlat2.xyz = (vec3(u_xlat13) * u_xlat2.xyz));
(vs_TEXCOORD3.xyz = (u_xlat2.xyz * unity_WorldTransformParams.www));
(vs_TEXCOORD3.w = u_xlat1.y);
(u_xlat2.x = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[0].xyz));
(u_xlat2.y = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[1].xyz));
(u_xlat2.z = dot(in_NORMAL0.xyz, hlslcc_mtx4x4unity_WorldToObject[2].xyz));
(u_xlat13 = dot(u_xlat2.xyz, u_xlat2.xyz));
(u_xlat13 = inversesqrt(u_xlat13));
(vs_TEXCOORD4.xyz = (vec3(u_xlat13) * u_xlat2.xyz));
(vs_TEXCOORD4.w = u_xlat1.z);
(u_xlat2 = (u_xlat1.yyyy * hlslcc_mtx4x4u_UniqueShadowMatrix[1]));
(u_xlat2 = ((hlslcc_mtx4x4u_UniqueShadowMatrix[0] * u_xlat1.xxxx) + u_xlat2));
(u_xlat1 = ((hlslcc_mtx4x4u_UniqueShadowMatrix[2] * u_xlat1.zzzz) + u_xlat2));
(u_xlat1 = (u_xlat1 + hlslcc_mtx4x4u_UniqueShadowMatrix[3]));
(vs_TEXCOORD5 = u_xlat1);
(u_xlat0.y = (u_xlat0.y * _ProjectionParams.x));
(u_xlat1.xzw = (u_xlat0.xwy * vec3(0.5, 0.5, 0.5)));
(vs_TEXCOORD6.zw = u_xlat0.zw);
(vs_TEXCOORD6.xy = (u_xlat1.zz + u_xlat1.xw));
return ;
}
